[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf
    storage.path  /fluent-bit/state

[INPUT]
    Name              tail
    Tag               suricata.eve
    Path              /logs/suricata/eve.json
    Parser            json
    DB                /fluent-bit/state/suricata.db
    Read_from_Head    true
    Refresh_Interval  10

[INPUT]
    Name              tail
    Tag               zeek.log
    Path              /logs/zeek/current/*.log,/logs/zeek/*.log
    Parser            zeek_tsv
    DB                /fluent-bit/state/zeek.db
    Read_from_Head    true
    Refresh_Interval  10

[INPUT]
    Name              tail
    Tag               wazuh.manager
    Path              /logs/wazuh-manager/**/*.log,/logs/wazuh-manager/*.log
    Parser            plain_text
    DB                /fluent-bit/state/wazuh-manager.db
    Read_from_Head    true
    Refresh_Interval  10

[INPUT]
    Name              tail
    Tag               vault.audit
    Path              /logs/vault/*.log
    Parser            plain_text
    DB                /fluent-bit/state/vault.db
    Read_from_Head    true
    Refresh_Interval  10

[INPUT]
    Name              tail
    Tag               openvas.log
    Path              /logs/openvas/*.log
    Parser            plain_text
    DB                /fluent-bit/state/openvas.db
    Read_from_Head    true
    Refresh_Interval  10

[FILTER]
    Name   modify
    Match  *
    Add    stack hq-sec-stack

[OUTPUT]
    Name                       gelf
    Match                      *
    Host                       graylog
    Port                       12201
    Mode                       udp
    Gelf_Short_Message_Key     log
    Gelf_Host_Key              source
